name = "dazzling_gleam"
version = "0.1.0"

description = "The long awaited PokéAPI client for Gleam."
licences = ["MIT"]
repository = { type = "github", user = "bekapod", repo = "dazzling_gleam" }
links = [{ title = "Repository", href = "https://github.com/bekapod/dazzling_gleam" }]

[dependencies]
gleam_stdlib = "~> 0.31"
gleam_http = "~> 3.5"
gleam_json = "~> 0.6"

[dev-dependencies]
gleeunit = "~> 0.10"
simplifile = "~> 0.1"
