name = "dazzling_gleam"
version = "0.1.0"

description = ""
licences = ["MIT"]
repository = { type = "github", user = "bekapod", repo = "dazzling_gleam" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.31"

[dev-dependencies]
gleeunit = "~> 0.10"
