name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "0.31.0"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - run: make format-check
      - run: make deps
      - run: make test-erlang
      - run: make test-javascript
